CREATE DATABASE IF NOT EXISTS SocialDB;

USE SocialDB;

DROP TABLE IF EXISTS user_data;

CREATE TABLE user_data(
    userID int NOT NULL AUTO_INCREMENT,
    username VARCHAR(24) NOT NULL,
    passwd VARCHAR(64) NOT NULL,
    # salt VARCHAR(12) NOT NULL,
    # hashedPassword VARCHAR(64) NOT NULL,
    PRIMARY KEY (userID), UNIQUE (username)
) AUTO_INCREMENT=1;
